### ISSUE TITLE
Inventory Summary Services

### ISSUE THREAD

**Issue by heubi76** [EdLeckert/wine-cellar#5]
Hello 
Thanks for the programming.
I installed it on HA but are not able to programm the Service Cards for:
wine_cellar.get_locations
wine_cellar.get_producers
wine_cellar.get_types
wine_cellar.get_varietals
wine_cellar.get_vintages

Would be nice if you show it online.
Regards Heubi

**Comment by EdLeckert** [comment]
Take another look at the documentation. I have expanded it to show what substitutions need to be made to use the `get_countries` example for the other services.

**Comment by heubi76** [comment]
Perfect...thanks a lot...



Von: Ed Leckert ***@***.***>
Gesendet: Sonntag, 27. Oktober 2024 19:56
An: EdLeckert/wine-cellar ***@***.***>
Cc: heubi76 ***@***.***>; Author ***@***.***>
Betreff: Re: [EdLeckert/wine-cellar] Inventory Summary Services (Issue #5)


Take another look at the documentation. I have expanded it to show what substitutions need to be made to use the get_countries example for the other services.

-
